name: Mirarr
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0
  flutter_dotenv: 5.1.0
  cached_network_image: 3.3.0
  intl: ^0.18.1
  url_launcher: ^6.2.5
  connectivity_plus: ^5.0.2
  internet_connection_checker_plus: ^2.2.0
  tmdb_api: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  webfeed_plus: ^1.0.0+1
  window_manager: ^0.3.8
  flutter_rating_bar: ^4.0.1
  package_info_plus: ^8.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/person.png
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf

